# Generated by Django 2.1.7 on 2019-03-31 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List_People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_column='Surname', max_length=50, verbose_name='Surname')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Name')),
                ('birthday', models.DateField(db_column='Birthday')),
                ('mobile_phone', models.CharField(db_column='Mobile phone', max_length=20)),
                ('user', models.ForeignKey(db_column='Author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
